### ISSUE TITLE
Telegram notification bot is not working

### ISSUE THREAD

**Issue by gopinath87607** [dennohpeter/MultiDexArbBot#3]
Hi the telegram notification is not working. I tried with monodb with node js connection seems like it's connecting to my bot but whenever I type /start in bot I  get error in vscode. Any guidance for configure telegram bot would be nice thanks in advance looking forward for flash loan version thanks sir.

**Comment by dennohpeter** [comment]
Hello @gopinath87607 , thanks for opening the issue, I have updated README to include steps of how to setup Telegram Bot and MongoDB, lemme know if that helps

**Comment by gopinath87607** [comment]
![Screenshot_20221026-075841_Telegram.jpg](https://user-images.githubusercontent.com/85057872/197920702-02ee48bc-74e4-43aa-9e52-258f5ae974c4.jpg) I am getting like this error
